#
# SensorNode production distro
#

require conf/distro/include/sensornode-base.inc

DISTRO = "sensornode"

SENSORNODE_KEYDIR = "${SENSORNODE_PRODUCT_KEYDIR}"

DISTRO_FEATURES:append = " \
    sensornode-ota \
    sensornode-hmi \
    sensornode-secureboot \
    sensornode-readonly \
"
