# Layer:  meta-sensornode
# Scope:  product — distro, images, application, OTA.

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sensornode"
BBFILE_PATTERN_sensornode = "^${LAYERDIR}/"
BBFILE_PRIORITY_sensornode = "10"

LAYERVERSION_sensornode        = "1"
LAYERDEPENDS_sensornode        = "core yocto openembedded-layer networking-layer qt5-layer swupdate sensornode-bsp"
LAYERSERIES_COMPAT_sensornode  = "kirkstone"
