#
# Layer:  meta-sensornode
# Path:   SensorNode-BBB/meta-sensornode
#

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sensornode"
BBFILE_PATTERN_sensornode = "^${LAYERDIR}/"
BBFILE_PRIORITY_sensornode = "10"

# Layer dependencies:
LAYERVERSION_sensornode        = "1"
LAYERDEPENDS_sensornode        = "core openembedded-layer swupdate sensornode-bsp"
LAYERSERIES_COMPAT_sensornode  = "kirkstone"
