require conf/distro/poky.conf

DISTRO = "sensornode"
DISTRO_NAME = "SensorNode"
DISTRO_VERSION = "1.0"

DISTRO_FEATURES:remove = " \
    x11 \
    wayland \
    opengl \
    vulkan \
    bluetooth \
    nfc \
    3g \
    ppp \
    pcmcia \
    wifi \
    alsa \
    pulseaudio \
    gobject-introspection-data \
    pci \
    zeroconf \
    debuginfod \
    multiarch \
"

DISTRO_FEATURES:append = " \
    systemd \
    secure-boot \
"

PACKAGECONFIG_DISTRO:pn-qtbase = " \
    linuxfb \
    tslib \
    fontconfig \
"

TOOLCHAIN_TARGET_TASK:append = " \
    libgpiod-dev \
    mosquitto-dev \
"

VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL_RUNTIME_initscripts = "systemd-compat-units"
