#@TYPE: Machine
#@NAME: bbb-sensornode
#@DESCRIPTION: BeagleBone Black with the SensorNode display and sensor board

require conf/machine/include/bbb-common.inc
require conf/machine/include/sensornode-hw.inc
