# Layer:  meta-sensornode-bsp
# Path:   SensorNode-BBB/meta-sensornode-bsp

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sensornode-bsp"
BBFILE_PATTERN_sensornode-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_sensornode-bsp = "6"

LAYERVERSION_sensornode-bsp        = "1"
LAYERDEPENDS_sensornode-bsp        = "core openembedded-layer qt5-layer"
LAYERSERIES_COMPAT_sensornode-bsp  = "kirkstone"
